version: '2.1'
services:
  mocka_openresty:
    mem_limit: 2048m
    image: mocka:latest
    entrypoint:  /scripts/loop.sh
    privileged: true
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./nginx:/usr/local/openresty/nginx/conf